version: '3'
services:
  btc:
    image: local/bitcoind
    container_name: bitcoind
    build: ./btc/
    ports:
      - "18400:18443"
      - "18444:18444"
    expose:
      - "18444"
    command: [ "-regtest", "-disablewallet", "--rpcbind=0.0.0.0","-whitelist=172.22.0.0/24","-addnode=omnicored:18444"]
    volumes:
      - ./volumes/btc/:/root/.bitcoin
  omnicored:
    image: ccr.ccs.tencentyun.com/omnicore/omnicored:0.0.3
    container_name: omnode
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: regnet.oblnd.top
    command: >-
      -server=1 -regtest=1
      -debug=0 -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcallowip=0.0.0.0/0
      -rpcport=18332 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002 -connect=bitcoind:18444
    volumes:
      - ./volumes/omnicored/:/home/bitcoin/.bitcoin
    expose:
      - '18332'
      - '18444'
      - '28332'
      - '28333'
    ports:
      - '18332:18332'
      - '28332:28332'
      - '28333:28333'